### ISSUE TITLE
More licensing options for wider compatibility?

### ISSUE THREAD

**Issue by Shnatsel** [kryptan/pcx#12]
First off, thank you for writing this crate!

There has recently been [interest](https://github.com/image-rs/image/pull/2364) in adding PCX support to the `image` crate via your `pcx` crate for use in a game restoration project. However, there are some concerns about adding a dependency with a WTFPL license, as it may create legal ambiguity for some users of the `image` crate.

Would you be open to adding MIT and Apache-2.0 as possible licensing options, in addition to WTFPL? The typical licensing in the Rust ecosystem is `MIT OR Apache-2.0`, so `WTFPL OR MIT OR Apache-2.0` would keep WTFPL as an option while also laying out clearly defined legal texts for those who might need that.

**Comment by mthiesen** [comment]
My contributions to this project have been quite small. Feel free to choose any licence you like.

**Comment by Shnatsel** [comment]
Thank you!

I see the license has been updated in git, so I'm going to go ahead and close this.

A release to crates.io would also be welcome, so that tools like [`cargo-deny`](https://github.com/EmbarkStudios/cargo-deny) wouldn't flag the crate.
